### ISSUE TITLE
Store initialization action should have a type field

### ISSUE THREAD

**Issue by AmaranthineCodices** [Roblox/rodux#12]
Rodux currently dispatches a blank action when creating the store:
https://github.com/Roblox/rodux/blob/12063b4fa9998713f3cd65c0e165c9c00fa956e6/lib/Store.lua#L31

This action should really have a `type` attribute like `__init` or something - maybe a symbol, maybe not. This tripped me up - I was expecting all actions to have a `type` field in the wake of #11.

**Comment by LPGhatguy** [comment]
Ooh, that's an oversight.

Should the initial action go through middleware? If so, I wonder if it should be a string like `@@INIT` like Redux to make it serializable.

**Comment by AmaranthineCodices** [comment]
I'm honestly not sure. I think it depends on how crucial we consider the initialization action. Middleware can outright cancel an action (in my implementation, at least), or tamper with it in any number of ways. If the initialization action is considered a "absolutely must be dispatched" sort of thing, then **no**, the initialization action should not go through the middleware.

**Comment by LPGhatguy** [comment]
I dug through all of the conversations the Redux team had about their initial action dispatching and how it relates to middleware, and I don´t think it needs to run through middleware.

In the worst case, if your middleware needs some sort of state, you can instantiate it:

```lua
local middlewareInstance = middleware({ options })
local store = Store.new(reducer, nil, { middlewareInstance })
```

I'll go ahead and fix this, since it's pretty easy to patch up and shouldn't cause conflicts with any existing PRs.
