### ISSUE TITLE
Add a Signal.Destroy method 

### ISSUE THREAD

**Issue by sayhisam1** [Roblox/rodux#48]
It would be nice to have an alternative mapping to Signal.disconnect - namely, Signal.Destroy.

This would make it play nicer with the popular Maid class by Quenty.

**Comment by LPGhatguy** [comment]
`disconnect` lines up with the [RBXScriptConnection API](https://developer.roblox.com/en-us/api-reference/datatype/RBXScriptConnection), roughly -- camelCase instead of PascalCase.

Maids can already handle disconnecting events, so it should be a matter of also supporting this casing. Alternatively, I believe it's possible to give Quenty's Maid class a function to call, which makes wrapping any existing libraries very easy.
